// <auto-generated />
using System;
using BolnickiSistem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BolnickiSistem.Migrations
{
    [DbContext(typeof(BolnicaContext))]
    partial class BolnicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BolnickiSistem.Models.Dijagnoza", b =>
                {
                    b.Property<int>("DijagnozaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DijagnozaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PregledId")
                        .HasColumnType("int");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DijagnozaId");

                    b.HasIndex("PregledId");

                    b.ToTable("Dijagnoze", (string)null);
                });

            modelBuilder.Entity("BolnickiSistem.Models.Dokument", b =>
                {
                    b.Property<int>("DokumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DokumentId"));

                    b.Property<DateTime>("DatumDodavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("DodaoKorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<int?>("PregledId")
                        .HasColumnType("int");

                    b.Property<string>("PutanjaDoFajla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipDokumenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DokumentId");

                    b.HasIndex("DodaoKorisnikId");

                    b.HasIndex("PacijentId");

                    b.HasIndex("PregledId");

                    b.ToTable("Dokumenti", (string)null);
                });

            modelBuilder.Entity("BolnickiSistem.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.HasIndex("UlogaId");

                    b.ToTable("Korisnici", (string)null);
                });

            modelBuilder.Entity("BolnickiSistem.Models.LaboratorijskiNalaz", b =>
                {
                    b.Property<int>("LaboratorijskiNalazId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaboratorijskiNalazId"));

                    b.Property<DateTime>("DatumAnalize")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jedinica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivAnalize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<int?>("PregledId")
                        .HasColumnType("int");

                    b.Property<string>("ReferentnaVrednost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rezultat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LaboratorijskiNalazId");

                    b.HasIndex("PacijentId");

                    b.HasIndex("PregledId");

                    b.ToTable("LaboratorijskiNalazi", (string)null);
                });

            modelBuilder.Entity("BolnickiSistem.Models.Pacijent", b =>
                {
                    b.Property<int>("PacijentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PacijentId"));

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alergije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojZdravstveneKartice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HronicneBolesti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KrvnaGrupa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LekarId")
                        .HasColumnType("int");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PacijentId");

                    b.HasIndex("BrojZdravstveneKartice")
                        .IsUnique();

                    b.HasIndex("JMBG")
                        .IsUnique();

                    b.HasIndex("LekarId");

                    b.ToTable("Pacijenti", (string)null);
                });

            modelBuilder.Entity("BolnickiSistem.Models.Pregled", b =>
                {
                    b.Property<int>("PregledId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PregledId"));

                    b.Property<DateTime?>("DatumKontrole")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPregleda")
                        .HasColumnType("datetime2");

                    b.Property<int>("LekarId")
                        .HasColumnType("int");

                    b.Property<string>("Nalaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("Preporuka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazlogDolaska")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Simptomi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PregledId");

                    b.HasIndex("LekarId");

                    b.HasIndex("PacijentId");

                    b.ToTable("Pregledi", (string)null);
                });

            modelBuilder.Entity("BolnickiSistem.Models.Terapija", b =>
                {
                    b.Property<int>("TerapijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerapijaId"));

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZavrsetka")
                        .HasColumnType("datetime2");

                    b.Property<string>("Doziranje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivLeka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PregledId")
                        .HasColumnType("int");

                    b.Property<string>("Ucestalost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uputstvo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TerapijaId");

                    b.HasIndex("PregledId");

                    b.ToTable("Terapije", (string)null);
                });

            modelBuilder.Entity("BolnickiSistem.Models.Uloga", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UlogaId");

                    b.ToTable("Uloge", (string)null);

                    b.HasData(
                        new
                        {
                            UlogaId = 1,
                            Naziv = "Administrator"
                        },
                        new
                        {
                            UlogaId = 2,
                            Naziv = "Lekar"
                        });
                });

            modelBuilder.Entity("BolnickiSistem.Models.Dijagnoza", b =>
                {
                    b.HasOne("BolnickiSistem.Models.Pregled", "Pregled")
                        .WithMany("Dijagnoze")
                        .HasForeignKey("PregledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregled");
                });

            modelBuilder.Entity("BolnickiSistem.Models.Dokument", b =>
                {
                    b.HasOne("BolnickiSistem.Models.Korisnik", "DodaoKorisnik")
                        .WithMany("Dokumenti")
                        .HasForeignKey("DodaoKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolnickiSistem.Models.Pacijent", "Pacijent")
                        .WithMany("Dokumenti")
                        .HasForeignKey("PacijentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolnickiSistem.Models.Pregled", "Pregled")
                        .WithMany("Dokumenti")
                        .HasForeignKey("PregledId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DodaoKorisnik");

                    b.Navigation("Pacijent");

                    b.Navigation("Pregled");
                });

            modelBuilder.Entity("BolnickiSistem.Models.Korisnik", b =>
                {
                    b.HasOne("BolnickiSistem.Models.Uloga", "Uloga")
                        .WithMany("Korisnici")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("BolnickiSistem.Models.LaboratorijskiNalaz", b =>
                {
                    b.HasOne("BolnickiSistem.Models.Pacijent", "Pacijent")
                        .WithMany("LaboratorijskiNalazi")
                        .HasForeignKey("PacijentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolnickiSistem.Models.Pregled", "Pregled")
                        .WithMany("LaboratorijskiNalazi")
                        .HasForeignKey("PregledId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Pacijent");

                    b.Navigation("Pregled");
                });

            modelBuilder.Entity("BolnickiSistem.Models.Pacijent", b =>
                {
                    b.HasOne("BolnickiSistem.Models.Korisnik", "Lekar")
                        .WithMany("Pacijenti")
                        .HasForeignKey("LekarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lekar");
                });

            modelBuilder.Entity("BolnickiSistem.Models.Pregled", b =>
                {
                    b.HasOne("BolnickiSistem.Models.Korisnik", "Lekar")
                        .WithMany("Pregledi")
                        .HasForeignKey("LekarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolnickiSistem.Models.Pacijent", "Pacijent")
                        .WithMany("Pregledi")
                        .HasForeignKey("PacijentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lekar");

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("BolnickiSistem.Models.Terapija", b =>
                {
                    b.HasOne("BolnickiSistem.Models.Pregled", "Pregled")
                        .WithMany("Terapije")
                        .HasForeignKey("PregledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregled");
                });

            modelBuilder.Entity("BolnickiSistem.Models.Korisnik", b =>
                {
                    b.Navigation("Dokumenti");

                    b.Navigation("Pacijenti");

                    b.Navigation("Pregledi");
                });

            modelBuilder.Entity("BolnickiSistem.Models.Pacijent", b =>
                {
                    b.Navigation("Dokumenti");

                    b.Navigation("LaboratorijskiNalazi");

                    b.Navigation("Pregledi");
                });

            modelBuilder.Entity("BolnickiSistem.Models.Pregled", b =>
                {
                    b.Navigation("Dijagnoze");

                    b.Navigation("Dokumenti");

                    b.Navigation("LaboratorijskiNalazi");

                    b.Navigation("Terapije");
                });

            modelBuilder.Entity("BolnickiSistem.Models.Uloga", b =>
                {
                    b.Navigation("Korisnici");
                });
#pragma warning restore 612, 618
        }
    }
}
